/**
 * generated by Xtext 2.12.0
 */
package m1ice.idm.generator;

import com.google.common.base.Objects;
import fr.inria.diverse.k3.al.annotationprocessor.Singleton;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.InputOutput;

@Singleton
@SuppressWarnings("all")
public final class Console {
  private Console() {
    // singleton
  }
  
  public String readLine(final String format, final Object... args) {
    try {
      java.io.Console _console = System.console();
      boolean _notEquals = (!Objects.equal(_console, null));
      if (_notEquals) {
        return System.console().readLine(format, args);
      }
      InputOutput.<String>println(String.format(format, args));
      InputStreamReader _inputStreamReader = new InputStreamReader(System.in);
      BufferedReader reader = new BufferedReader(_inputStreamReader);
      return reader.readLine();
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  private final static Console INSTANCE = new Console();
  
  public static Console getInstance() {
    return INSTANCE;
  }
}
