/*
 * generated by Xtext 2.12.0
 */
package m1ice.idm.ide

import com.google.inject.Guice
import m1ice.idm.Lab2RuntimeModule
import m1ice.idm.Lab2StandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Lab2IdeSetup extends Lab2StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Lab2RuntimeModule, new Lab2IdeModule))
	}
	
}
