/**
 * generated by Xtext 2.12.0
 */
package m1ice.idm.validation;

import m1ice.idm.validation.AbstractLab2Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Lab2Validator extends AbstractLab2Validator {
}
