/*
 * generated by Xtext 2.12.0
 */
package m1ice.idm.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class Lab2ScopeProvider extends AbstractLab2ScopeProvider {

}
