/**
 * generated by Xtext 2.12.0
 */
package m1ice.idm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import m1ice.idm.Lab2RuntimeModule;
import m1ice.idm.Lab2StandaloneSetup;
import m1ice.idm.ide.Lab2IdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Lab2IdeSetup extends Lab2StandaloneSetup {
  @Override
  public Injector createInjector() {
    Lab2RuntimeModule _lab2RuntimeModule = new Lab2RuntimeModule();
    Lab2IdeModule _lab2IdeModule = new Lab2IdeModule();
    return Guice.createInjector(Modules2.mixin(_lab2RuntimeModule, _lab2IdeModule));
  }
}
