/**
 * generated by Xtext 2.12.0
 */
package m1ice.idm.ide;

import m1ice.idm.ide.AbstractLab2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Lab2IdeModule extends AbstractLab2IdeModule {
}
