/**
 * generated by Xtext 2.12.0
 */
package m1ice.idm.ui;

import m1ice.idm.ui.AbstractLab2UiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Lab2UiModule extends AbstractLab2UiModule {
  public Lab2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
