/**
 * generated by Xtext 2.12.0
 */
package m1ice.idm;

import m1ice.idm.Lab2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Lab2StandaloneSetup extends Lab2StandaloneSetupGenerated {
  public static void doSetup() {
    new Lab2StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
