/**
 * generated by Xtext 2.12.0
 */
package m1ice.idm;

import m1ice.idm.AbstractLab2RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Lab2RuntimeModule extends AbstractLab2RuntimeModule {
}
