/**
 * generated by Xtext 2.12.0
 */
package m1ice.idm.ui.contentassist;

import m1ice.idm.ui.contentassist.AbstractLab2ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Lab2ProposalProvider extends AbstractLab2ProposalProvider {
}
