/**
 * generated by Xtext 2.12.0
 */
package m1ice.idm.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import m1ice.idm.lab1.State;
import m1ice.idm.lab1.StateMachine;
import m1ice.idm.lab1.Transition;
import m1ice.idm.services.Lab2GrammarAccess;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class Lab2Formatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private Lab2GrammarAccess _lab2GrammarAccess;
  
  protected void _format(final StateMachine stateMachine, @Extension final IFormattableDocument document) {
    EList<State> _states = stateMachine.getStates();
    for (final State state : _states) {
      document.<State>format(state);
    }
    EList<Transition> _transitions = stateMachine.getTransitions();
    for (final Transition transition : _transitions) {
      document.<Transition>format(transition);
    }
  }
  
  public void format(final Object stateMachine, final IFormattableDocument document) {
    if (stateMachine instanceof XtextResource) {
      _format((XtextResource)stateMachine, document);
      return;
    } else if (stateMachine instanceof StateMachine) {
      _format((StateMachine)stateMachine, document);
      return;
    } else if (stateMachine instanceof EObject) {
      _format((EObject)stateMachine, document);
      return;
    } else if (stateMachine == null) {
      _format((Void)null, document);
      return;
    } else if (stateMachine != null) {
      _format(stateMachine, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(stateMachine, document).toString());
    }
  }
}
